# Generated by Django 6.0.2 on 2026-02-19 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('version', models.CharField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('order', models.PositiveIntegerField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessmenttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('prompt', models.TextField()),
                ('kind', models.CharField(choices=[('text', 'Text'), ('fill_blanks', 'Fill in the blanks'), ('reorder', 'Reorder'), ('match', 'Matching'), ('mcq', 'Multiple choice')], default='text', max_length=20)),
                ('max_marks', models.PositiveSmallIntegerField(default=9)),
                ('spec_json', models.TextField(blank=True, default='')),
                ('answer_key_json', models.TextField(blank=True, default='')),
                ('marking_notes', models.TextField(blank=True, default='')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.section')),
            ],
            options={
                'ordering': ['section__order', 'order', 'code'],
            },
        ),
    ]
