# Generated by Django 6.0.2 on 2026-02-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField()),
                ('surname', models.CharField()),
                ('id_number', models.CharField(max_length=13, unique=True)),
                ('dob', models.DateField(blank=True, default='')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Please select your gender.', max_length=20)),
                ('demographic', models.CharField(choices=[('African', 'African'), ('Coloured', 'Coloured'), ('Indian', 'Indian'), ('White', 'White')], default='Please select your race.', max_length=20)),
            ],
        ),
    ]
