# Generated by Django 6.0.2 on 2026-02-20 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_learner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenttemplate',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='assessmenttemplate',
            name='version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='learner',
            name='demographic',
            field=models.CharField(choices=[('African', 'African'), ('Coloured', 'Coloured'), ('Indian', 'Indian'), ('White', 'White')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='learner',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='first_names',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='learner',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='learner',
            name='surname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('honesty_name', models.CharField(blank=True, default='', max_length=200)),
                ('honesty_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.learner')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessmenttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_json', models.TextField(blank=True, default='')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.question')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question'), name='uniq_attempt_question')],
            },
        ),
    ]
