# Generated by Django 6.0.2 on 2026-02-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_alter_section_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='code',
            field=models.CharField(default='OU2X2MQW', max_length=32, unique=True),
        ),
    ]
