# Generated by Django 6.0.2 on 2026-02-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0012_alter_attempt_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='code',
            field=models.CharField(default='YFCMQP4Z', max_length=32, unique=True),
        ),
    ]
