# Generated by Django 6.0.2 on 2026-02-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0013_alter_attempt_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='code',
            field=models.CharField(default='SNY98JK6', max_length=32, unique=True),
        ),
    ]
