# Generated by Django 6.0.2 on 2026-02-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0014_alter_attempt_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='code',
            field=models.CharField(default='SY4BOQL6', max_length=32, unique=True),
        ),
    ]
