# Generated by Django 6.0.2 on 2026-02-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0015_alter_attempt_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='code',
            field=models.CharField(default='5801GNQJ', max_length=32, unique=True),
        ),
    ]
