# Generated by Django 6.0.2 on 2026-02-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0016_alter_attempt_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='code',
            field=models.CharField(default='7PPDGWIF', max_length=32, unique=True),
        ),
    ]
