# Generated by Django 6.0.2 on 2026-03-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0017_alter_attempt_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='code',
            field=models.CharField(default='GY15R07S', max_length=32, unique=True),
        ),
    ]
