# Generated by Django 6.0.2 on 2026-04-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessment",
            "0018_assessmenttemplate_created_by_alter_attempt_code_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="learner",
            name="id_number",
            field=models.CharField(
                blank=True, default=None, max_length=13, null=True, unique=True
            ),
        ),
    ]
