# Generated by Django 6.0.2 on 2026-03-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0018_alter_attempt_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="code",
            field=models.CharField(default="WSCQZ4ZD", max_length=32, unique=True),
        ),
    ]
