# Generated by Django 6.0.2 on 2026-03-09 13:29

import assessment.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0020_alter_attempt_code_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmenttemplate",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                blank=True,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="code",
            field=models.CharField(
                default=assessment.models.generate_attempt_code,
                max_length=32,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="response",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="assessment.response"
            ),
        ),
    ]
