# Generated by Django 6.0.2 on 2026-04-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0020_attempt_current_question_examsession_attempt_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="kind",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("fill_blanks", "Fill in the blanks"),
                    ("reorder", "Reorder"),
                    ("match", "Matching"),
                    ("mcq", "Multiple choice"),
                    ("long_division", "Long division"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
