# Generated by Django 6.0.2 on 2026-04-14 10:31

import json
from django.db import migrations


def update_num_a4(apps, schema_editor):
    Question = apps.get_model("assessment", "Question")
    try:
        q = Question.objects.get(code="NUM-A-4")
        q.kind = "long_division"
        q.prompt = "4) 84 ÷ 4 = ?"
        q.spec_json = json.dumps({"dividend": 84, "divisor": 4, "num_digits": 2})
        q.answer_key_json = json.dumps({"auto_mark": True, "answers": ["21"]})
        q.save()
    except Question.DoesNotExist:
        pass


def reverse_num_a4(apps, schema_editor):
    Question = apps.get_model("assessment", "Question")
    try:
        q = Question.objects.get(code="NUM-A-4")
        q.kind = "text"
        q.prompt = "4) 84 ÷ 4 ="
        q.spec_json = ""
        q.answer_key_json = ""
        q.save()
    except Question.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0021_add_long_division_kind"),
    ]

    operations = [
        migrations.RunPython(update_num_a4, reverse_num_a4),
    ]
