# Generated by Django 6.0.2 on 2026-04-14 11:41

import json
from django.db import migrations


def revert_num_a4(apps, schema_editor):
    Question = apps.get_model("assessment", "Question")
    try:
        q = Question.objects.get(code="NUM-A-4")
        q.kind = "text"
        q.prompt = "4) 84 ÷ 4 ="
        q.spec_json = ""
        q.answer_key_json = json.dumps({"auto_mark": True, "answers": ["21"]})
        q.save()
    except Question.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0022_update_num_a4_long_division"),
    ]

    operations = [
        migrations.RunPython(revert_num_a4, migrations.RunPython.noop),
    ]
