# Generated by Django 6.0.2 on 2026-04-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0023_revert_num_a4_to_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
