# Generated by Django 6.0.2 on 2026-04-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0024_question_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="review_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attempt",
            name="section_timings_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
