# Generated by Django 6.0.4 on 2026-04-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0039_clear_needs_review_on_automarked_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('logo_url', models.CharField(blank=True, max_length=300)),
                ('logo_white_url', models.CharField(blank=True, max_length=300)),
                ('favicon_url', models.CharField(blank=True, max_length=300)),
                ('logo_alt', models.CharField(blank=True, max_length=120)),
                ('banner_url', models.CharField(blank=True, max_length=300)),
                ('color_primary', models.CharField(default='#1a1a2e', max_length=7)),
                ('color_secondary', models.CharField(default='#16213e', max_length=7)),
                ('color_accent', models.CharField(default='#0f3460', max_length=7)),
                ('color_text', models.CharField(default='#111111', max_length=7)),
                ('color_bg', models.CharField(default='#ffffff', max_length=7)),
                ('font_family_primary', models.CharField(default='Arial, sans-serif', max_length=100)),
                ('font_family_secondary', models.CharField(blank=True, max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('footer_line', models.CharField(blank=True, max_length=300)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('website_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tenant',
            },
        ),
    ]
