# Generated by Django 6.0.4 on 2026-04-19 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0040_add_tenant_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=10)),
                ('mode', models.CharField(blank=True, max_length=10)),
                ('points_before', models.FloatField(blank=True, null=True)),
                ('points_after', models.FloatField()),
                ('max_points', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='assessment.score')),
            ],
            options={
                'verbose_name': 'Score audit entry',
                'verbose_name_plural': 'Score audit log',
                'ordering': ['changed_at'],
            },
        ),
    ]
