# Generated by Django 6.0.4 on 2026-04-25 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0042_rename_abandoned_to_incomplete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttemplate',
            name='moderation_mode',
            field=models.CharField(choices=[('audit', 'Audit only — moderator reads, cannot re-mark'), ('full', 'Full — moderator can unlock and re-mark')], default='audit', max_length=10),
        ),
        migrations.AddField(
            model_name='attempt',
            name='finalised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='finalised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalised_attempts', to=settings.AUTH_USER_MODEL),
        ),
    ]
