# Generated by Django 6.0.4 on 2026-05-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0047_attempt_workstation_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='consent_signature_png',
        ),
    ]
