# Generated by Django 6.0.5 on 2026-06-06 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0058_fix_section_durations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['status'], name='attempt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['status', 'finalised_at'], name='attempt_status_finalised_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['submitted_at'], name='attempt_submitted_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['last_activity_at'], name='attempt_last_activity_idx'),
        ),
    ]
