# Generated by Django 6.0.6 on 2026-06-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0059_attempt_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='worksheet_print_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
