# Generated by Django 6.0.6 on 2026-07-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0060_worksheet_print_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='accommodation_notes',
            field=models.TextField(blank=True, default='', help_text='Optional assessor note on why an accommodation was set (not shown to the learner).'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='extended_time_multiplier',
            field=models.FloatField(default=1.0, help_text='Extended-time accommodation applied to every clock for this attempt (assessment duration, section slots, review windows). 1.0 = no accommodation, 1.5 = +50% time, 2.0 = +100% time.'),
        ),
    ]
