# Generated by Django 6.0.6 on 2026-07-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0064_require_tenant_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='id_number',
            field=models.CharField(blank=True, default=None, max_length=13, null=True),
        ),
        migrations.AddConstraint(
            model_name='learner',
            constraint=models.UniqueConstraint(condition=models.Q(('id_number__isnull', False)), fields=('tenant', 'id_number'), name='uniq_tenant_id_number'),
        ),
    ]
