from django.urls import path
from . import views

app_name = "assessment"

urlpatterns = [
    path("accounts/register/<uuid:token>/", views.register, name="register"),
    path("assessor/invite/", views.generate_invite, name="generate_invite"),
    path("", views.home, name="home"),
    path("demo/request/", views.request_demo, name="request_demo"),
    path("start/", views.start, name="start"),
    path("attempt/<str:code>/details/", views.attempt_details, name="attempt_details"),
    path("attempt/<str:code>/consent/", views.attempt_consent, name="attempt_consent"),
    path("attempt/<str:code>/instructions/", views.attempt_instructions, name="attempt_instructions"),
    path("attempt/<str:code>/q/<int:n>/", views.attempt_question, name="attempt_question"),
    path("attempt/<str:code>/submit/", views.attempt_submit, name="attempt_submit"),
    path("attempt/<str:code>/review/<int:section_id>/", views.attempt_section_review_info, name="attempt_section_review_info"),
    path("attempt/<str:code>/review/<int:section_id>/q/<int:n>/", views.attempt_section_review_question, name="attempt_section_review_question"),
    path("attempt/<str:code>/review/<int:section_id>/done/", views.attempt_section_review_done, name="attempt_section_review_done"),
    path("attempt/<str:code>/submitted/", views.attempt_submitted, name="attempt_submitted"),
    path("assessor/", views.assessor_dashboard, name="assessor_dashboard"),
    path("assessor/metrics/", views.assessor_metrics, name="assessor_metrics"),
    path("assessor/metrics/simulate/", views.assessor_metrics_simulate, name="assessor_metrics_simulate"),
    path("assessor/guide/", views.assessor_guide, name="assessor_guide"),
    path("assessor/attempts/", views.assessor_attempts, name="assessor_attempts"),
    path("assessor/review-queue/", views.assessor_review_queue, name="assessor_review_queue"),
    path("assessor/attempts/new/", views.assessor_new_attempt, name="assessor_new_attempt"),
    path("assessor/attempts/<str:code>/mark/", views.assessor_mark_attempt, name="assessor_mark_attempt"),
    path("assessor/attempts/<str:code>/unlock/", views.assessor_unlock_attempt, name="assessor_unlock_attempt"),
    path("assessor/attempts/<str:code>/approve/", views.assessor_approve_moderation, name="assessor_approve_moderation"),
    path("assessor/moderation/", views.assessor_moderation, name="assessor_moderation"),
    path("assessor/archive/", views.assessor_archive, name="assessor_archive"),
    path("assessor/activity/", views.assessor_activity_report, name="assessor_activity_report"),
    path("assessor/attempts/<str:code>/auditor-reopen/", views.assessor_auditor_reopen, name="assessor_auditor_reopen"),
    path("assessor/attempts/<str:code>/auto-marked/", views.assessor_auto_marked_attempt, name="assessor_auto_marked_attempt"),
    path("assessor/questions/", views.assessor_questions, name="assessor_questions"),
    path("assessor/questions/<int:pk>/toggle/", views.assessor_toggle_question, name="assessor_toggle_question"),
    path("assessor/results/", views.assessor_results, name="assessor_results"),
    path("assessor/results/export/", views.assessor_results_export, name="assessor_results_export"),
    path("assessor/sessions/", views.assessor_sessions, name="assessor_sessions"),
    path("assessor/sessions/new/", views.assessor_new_session, name="assessor_new_session"),
    path("assessor/sessions/<str:code>/monitor/", views.session_monitor, name="session_monitor"),
    path("session/<str:code>/join/", views.session_join, name="session_join"),
    path("session/<str:code>/consent/", views.session_consent, name="session_consent"),
    path("assessor/attempts/<str:code>/scoring-breakdown/", views.assessor_scoring_breakdown, name="assessor_scoring_breakdown"),
    path("assessor/attempts/<str:code>/audit-log/", views.assessor_score_audit_log, name="assessor_score_audit_log"),
    path("assessor/attempts/<str:code>/working-sheet/upload/", views.assessor_working_sheet_upload, name="assessor_working_sheet_upload"),
    path("assessor/attempts/<str:code>/working-sheet/image/", views.assessor_working_sheet_image, name="assessor_working_sheet_image"),
    path("assessor/attempts/<str:code>/working-sheet/print/", views.assessor_working_sheet_print, name="assessor_working_sheet_print"),
    path("assessor/attempts/<str:code>/writing-submission/upload/", views.assessor_writing_submission_upload, name="assessor_writing_submission_upload"),
    path("assessor/attempts/<str:code>/writing-submission/image/", views.assessor_writing_submission_image, name="assessor_writing_submission_image"),
    path("assessor/account/role/", views.set_active_role, name="set_active_role"),
    path("error-report/", views.error_report, name="error_report"),
    path("assessor/error-preview/<int:code>/", views.error_preview, name="error_preview"),
]
